#cloud-config
disable_root: true
timezone: Asia/Novosibirsk
repo_update: true
repo_upgrade: true
apt:
  preserve_sources_list: true

packages:
#  - epel-release
  - nginx
#
runcmd:
  - [ systemctl, enable, nginx.service ]
  - [ systemctl, start, --no-block, nginx.service ]
  - [ chown -R ansible:www-data /var/www/html ]
  - [ sh, -c, "echo '<html><p>Application Load Balancer\n</p></html>' > /var/www/html/index.html"]
  - [ sh, -c, "echo $(hostname | cut -d '.' -f 1 ) >> /var/www/html/index.html" ]


users:
 - name: ansible
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCraA7RWGzeAkj5UY9P5BM2J1fNT7G8dyXbwWiX9l1/GYSns2COG+QOT820TKxuBcuFD6DzsaUlG6XP51tAaOmu7f3fO0n0n5hk4DFIx8quDdU8LjCr/lMOiYnBngMNGKJhZfduiXnOGyvhlIwUNRwVQNbR/Fq5d6klqkaRh0nuITUJcz4lG3ePpi0ZVgA79EC8sHCwZcqndGeb+ZwfDS02WyhnO+ajSdzV6TrWNHguQPCc4JVaQBsBkVpvLMS0eWu52smXtkrE7rrvlXrVIkehOzlF3IGXNpURjuyNHrR71+Eu0Qq/OIzAHM+idaHCj2TcUFg0irM8PoyHnB8d9AZicLQsd5QprBn5p/zK+T/IG++dPGHG+Ynm7USg5BLIax69ED4EYh3FN2DMEgoLe42we6hc7pqRa6FzFxYMxUOGuDsbiFyXJU1+yVVTh79cHC/DTuBs3iTBWPwNepxXKSsHymyha2zqsb1F65Q9X2dcWrwam/94h0OPT0oAGn9r0G0= nedorezov@GARRO
