all:
  children:

    jump:
      hosts:
        bastion:
          ansible_host: 84.252.141.113
      vars:
        ansible_ssh_common_args:
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

    webservers:
      hosts:
        webserver-adat:
          ansible_host: 192.168.2.30
        webserver-opev:
          ansible_host: 192.168.3.27
        webserver-izev:
          ansible_host: 192.168.1.17

    observability:
      hosts:
        prometheus:
          ansible_host: 192.168.4.26
        grafana:
          ansible_host: 192.168.10.16
        elastic:
          ansible_host: 192.168.4.3
        kibana:
          ansible_host: 192.168.10.31
  vars:
    ansible_ssh_common_args: '-J ansible@84.252.141.113'
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    ansible_user: ansible
    ansible_become: true
