
- name: Setup docker engine and python plugins for docker compose
  hosts:
    - observability
    - webservers
  roles:
    - docker-host

- name: Elasticsearch setup
  hosts: elastic
  roles:
    - elasticsearch

- name: Kibana setup
  hosts: kibana
  roles:
    - kibana

- name: Configure Web Servers instance group
  hosts: webservers
  roles:
    - node-exporter
    - nginx-log-exporter

#    - name: Prometheus setup
#      hosts: prometheus
#      roles:
#        - prometheus
#        - pg-prom-adapter



#
#- name: Grafana setup
#  hosts: grafana
#  roles:
#    - grafana
#    - alertmanager
#

#
#- name: Configure filebeats
#  hosts:
#    - observability
#    - webservers
#  roles:
#    - filebeat